---
- name: create service play
  hosts: shesh
  become: false
  tasks:
    - name: Create directory
      command: mkdir -p /home/shesh/k8s/

    - name: Copy script to remote hosts
      copy:
        src: create-service.sh
        dest: /home/shesh/k8s/create-service.sh
        mode: 0755
  
    - name: Copy k8s-specifications directory
      synchronize:
        src: k8s-specifications
        dest: /home/shesh/k8s/k8s-specifications/

    - name: Change directory
      command: cd /home/shesh/k8s/
      
    - name: Execute create-service.sh script
      script: ./create-service.sh