---
- name: create service play
  hosts: webservergroup
  become: false
  tasks:
    - name: Remove existing directory
      command: rm -rf ~/k8s/

    - name: Create directory
      command: mkdir -p ~/k8s/

    - name: Copy script to remote hosts
      copy:
        src: create-service.sh
        dest: ~/k8s/create-service.sh
        mode: 0755
  
    - name: Copy k8s-specifications directory
      synchronize:
        src: k8s-specifications
        dest: ~/k8s/

    - name: show contents of k8s directory
      command: ls ~/k8s/

    - name: Execute create-service.sh script
      script: ~/k8s/create-service.sh