apiVersion: apps/v1
kind: Deployment
metadata:
  name: staffs-info-app-db-deployment
  labels:
    app: staffs-info-app-db
    type: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staffs-info-app-db
  template:
    metadata:
      labels:
        app: staffs-info-app-db
    spec:
      containers:
      - name: staffs-info-app-db-cont
        image: rabnmgr7/staffs-info-app-db:$BUILD_NUMBER
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: staffs-info-app-db-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: staffs-info-app-db-config
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: staffs-info-app-db-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: staffs-info-app-db-secret
              key: MYSQL_PASSWORD
