apiVersion: v1
kind: Service
metadata:
  name: staffs-info-app-node-svc
spec:
  type: LoadBalancer
  selector:
    app: staffs-info-app-node-deployment
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8123
