apiVersion: v1
kind: Service
metadata:
  name: staffs-info-app-node-svc
spec:
  selector:
    app: staffs-info-app-node-deployment
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8085
  type: clusterIP
