apiVersion: apps/v1
kind: Deployment
metadata:
  name: staffs-info-app-node-deployment
  labels:
    app: staffs-info-app-node-deployment
    type: front-end
spec:
  replicas: 3
  template:
    metadata:
      name: staffs-info-app-node-deployment
      labels:
        app: staffs-info-app-node-deployment
    spec:
      containers:
        - name: staffs-info-app-node-cont
          image: rabnmgr7/staffs-info-app-node:latest
          ports:
          - containerPort: 8123
          env:
          - name: DATABASE_HOST
            value: staffs-info-app-db-svc
          command:
            - "/bin/bash"
            - "-c"
          args:
            - "/app/start.sh"
  selector:
    matchLabels:
      app: staffs-info-app-node-deployment
