apiVersion: v1
kind: Service
metadata:
  name: staffs-info-app-node-svc
spec:
  type: NodePort
  selector:
    app: staffs-info-app-node-deployment
  ports:
    - protocol: TCP
      port: 30010
      targetPort: 8123
      nodePort: 30010
